version: '3.8'

services:
  youtube_videos:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    container_name: youtube_videos
    volumes:
      - ./storage:/app/storage/
      - ./assets:/app/assets
      - ./scripts:/app/scripts
      - ./config/.env:/app/config/.env
      - ./tests:/app/tests
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: tail -f /dev/null 
